export const specialties = [
  //   "Alergologia",
  "Anestesiologia",
  "Angiologia",
  "Cancerologia",
  "Cardiologia",
  "Cirurgia Cardiovascular",
  "Cirurgia de Cabeça e Pescoço",
  "Cirurgia do Aparelho Digestivo",
  "Cirurgia Geral",
  "Cirurgia Pediátrica",
  "Cirurgia Plástica",
  //   "Cirurgia Torácica",
  "Cirurgia Vascular",
  "Clínica Médica",
  "Dermatologia",
  "Endocrinologia e Metabologia",
  "Endoscopia",
  "Gastroenterologia",
  "Geriatria",
  "Ginecologia e Obstetrícia",
  "Hematologia e Hemoterapia",
  "Hepatologia",
  "Homeopatia",
  //   "Infectologia",
  "Mastologia",
  "Medicina de Emergência",
  //   "Medicina do Esporte",
  "Medicina do Trabalho",
  "Medicina de Família e Comunidade",
  //   "Medicina Física e Reabilitação",
  "Medicina Intensiva",
  "Medicina Legal e Perícia Médica",
  "Nefrologia",
  "Neurocirurgia",
  "Neurologia",
  "Nutrologia",
  "Oftalmologia",
  "Oncologia Clínica",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Patologia",
  "Patologia Clínica/Medicina Laboratorial",
  "Pediatria",
  // "Pneumologia"
  "Psiquiatria",
  "Radiologia e Diagnóstico por Imagem",
  "Radioterapia",
  "Reumatologia",
  "Urologia",
] as const;

export type Specialty = (typeof specialties)[number];

export function isSpecialty(value: string): value is Specialty {
  return specialties.includes(value as Specialty);
}
